title: Gabriel Aloho
author: Gabriel Aloho
theme: minima
email: alohoaondoaver@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This sites is about Gabriel Aloho. It tells his journey in IT and the projects he has done since
  becoming a programmer.

# social links
twitter_username:  https://twitter.com/AlohoGabriel # DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/gabrielaloho # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
